# Common configuration for ArduPilot autopilot
#
# node:
startup_px4_usb_quirk: false

# --- system plugins ---

# sys_status & sys_time connection options
conn:
  heartbeat_rate: 1.0    # send heartbeat rate in Hertz
  timeout: 10.0          # heartbeat timeout in seconds
  timesync_rate: 10.0    # TIMESYNC rate in Hertz (feature disabled if 0.0)
  system_time_rate: 1.0  # send system time to FCU rate in Hertz (disabled if 0.0)

# sys_status
sys:
  min_voltage: 10.0   # diagnostics min voltage
  disable_diag: false # disable all sys_status diagnostics, except heartbeat

# sys_time
time:
  time_ref_source: "fcu"  # time_reference source
  timesync_avg_alpha: 0.6 # timesync averaging factor

# --- mavros plugins (alphabetical order) ---

# global_position
global_position:
  frame_id: "fcu"           # pose and fix frame_id
  rot_covariance: 99999.0   # covariance for attitude?
  tf:
    send: false               # send TF?
    frame_id: "local_origin"  # TF frame_id
    child_frame_id: "fcu_utm" # TF child_frame_id

# imu_pub
imu:
  frame_id: "fcu"
  linear_acceleration_stdev: 0.0003
  angular_velocity_stdev: 0.0003490659
  orientation_stdev: 1.0
  magnetic_stdev: 0.0

# local_position
local_position:
  frame_id: "local_origin"
  tf:
    send: true
    frame_id: "local_origin"
    child_frame_id: "fcu"
    send_fcu: false

# setpoint_position
setpoint_position:
  tf:
    listen: false           # enable tf listener (disable topic subscribers)
    frame_id: "local_origin"
    child_frame_id: "setpoint"
  mav_frame: LOCAL_NED
